#define SIMBOL_1
#define SIMBOL_2
#define SIMBOL_3
#define SIMBOL_4
#define SIMBOL_5
#define SIMBOL_6
#define SIMBOL_7
#define SIMBOL_8
#define SIMBOL_9
#define SIMBOL_0
#define SIMBOL_-
#define SIMBOL_/
#define SIMBOL_:
#define SIMBOL_;
#define SIMBOL_(
#define SIMBOL_)
#define SIMBOL_$
#define SIMBOL_&
#define SIMBOL_@
#define SIMBOL_"
#define SIMBOL_.
#define SIMBOL_,
#define SIMBOL_?
#define SIMBOL_!
#define SIMBOL_'
